{{- if .Values.rabbitmq.enabled }}

{{- $images := .Values.images | default dict -}}
{{- $rabbitImg := get $images "rabbitmq" | default dict -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespaces.data | default "ns-data" }}
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: {{ .Values.rabbitmq.replicas | default 1 }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ $rabbitImg.repository | default "rabbitmq" }}:{{ $rabbitImg.tag | default "3-management" }}"
          imagePullPolicy: {{ $images.pullPolicy | default "IfNotPresent" }}

          ports:
            - containerPort: {{ .Values.rabbitmq.ports.amqp.containerPort | default 5672 }}
            - containerPort: {{ .Values.rabbitmq.ports.management.containerPort | default 15672 }}

          env:
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.data.name | quote }}
                  key: {{ .Values.secrets.data.rabbitmqUsernameKey | quote }}

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.data.name | quote }}
                  key: {{ .Values.secrets.data.rabbitmqPasswordKey | quote }}
{{- end }}
