{{- if .Values.userData.enabled }}

{{- $images := .Values.images | default dict -}}
{{- $userDataImg := get $images "userData" | default dict -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-data
  namespace: {{ .Values.namespaces.data | default "ns-data" }}
  labels:
    app: user-data
spec:
  serviceName: user-data
  replicas: {{ .Values.userData.replicas | default 1 }}
  selector:
    matchLabels:
      app: user-data
  template:
    metadata:
      labels:
        app: user-data
    spec:
      containers:
        - name: user-data
          image: "{{ $userDataImg.repository | default "redis" }}:{{ $userDataImg.tag | default "6-alpine" }}"
          imagePullPolicy: {{ $images.pullPolicy | default "Always" }}

          ports:
            - containerPort: 6379
              name: redis-port

          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: {{ .Values.userData.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.userData.readinessProbe.periodSeconds | default 10 }}

          resources:
            requests:
              cpu: {{ .Values.userData.resources.requests.cpu | default "500m" | quote }}
              memory: {{ .Values.userData.resources.requests.memory | default "2000Mi" | quote }}
            limits:
              cpu: {{ .Values.userData.resources.limits.cpu | default "1" | quote }}
              memory: {{ .Values.userData.resources.limits.memory | default "2000Mi" | quote }}

  volumeClaimTemplates:
    - metadata:
        name: user-storage
      spec:
        accessModes:
          - {{ .Values.userData.persistence.accessMode | default "ReadWriteOnce" | quote }}
        resources:
          requests:
            storage: {{ .Values.userData.persistence.size | default "5Gi" | quote }}

{{- end }}